// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvhV2sisHE4kHtXp2OFijaqkAintNYylM',
    appId: '1:111511852499:web:85d29b8081fc8d334f8b26',
    messagingSenderId: '111511852499',
    projectId: 'get-pass-e77e5',
    authDomain: 'get-pass-e77e5.firebaseapp.com',
    storageBucket: 'get-pass-e77e5.firebasestorage.app',
    measurementId: 'G-FP05P6VXMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL-4eewuwjLCYzZbSCpJ16aJ3aopxlpa0',
    appId: '1:111511852499:android:4f51b30fc66927eb4f8b26',
    messagingSenderId: '111511852499',
    projectId: 'get-pass-e77e5',
    storageBucket: 'get-pass-e77e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANOth9bGTLDtWnp8f-hMkBgZrTN8DxUSs',
    appId: '1:111511852499:ios:3b69d43e4a04dea44f8b26',
    messagingSenderId: '111511852499',
    projectId: 'get-pass-e77e5',
    storageBucket: 'get-pass-e77e5.firebasestorage.app',
    iosBundleId: 'com.getpass.getpass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANOth9bGTLDtWnp8f-hMkBgZrTN8DxUSs',
    appId: '1:111511852499:ios:3b69d43e4a04dea44f8b26',
    messagingSenderId: '111511852499',
    projectId: 'get-pass-e77e5',
    storageBucket: 'get-pass-e77e5.firebasestorage.app',
    iosBundleId: 'com.getpass.getpass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvhV2sisHE4kHtXp2OFijaqkAintNYylM',
    appId: '1:111511852499:web:40639c4ed37078dc4f8b26',
    messagingSenderId: '111511852499',
    projectId: 'get-pass-e77e5',
    authDomain: 'get-pass-e77e5.firebaseapp.com',
    storageBucket: 'get-pass-e77e5.firebasestorage.app',
    measurementId: 'G-MXWGBNFVGH',
  );
}
